import datetime

date = datetime.datetime.now()
print("Current date and time: ", date)
print("Timestamps: ", date.timestamp())
print("Full Date: ", date.date())
print("Year: ", date.year)
print("Month: ", date.month)
print("Date: ", date.day)
print("Week day(weekday() monday=0): ", date.weekday())
print("Hour: ", date.hour)
print("Minute: ", date.minute)
print("Seconds: ", date.second)
print("Microseconds: ", date.microsecond)

print("\nUsing Formate function:\n")
print("Year: ", date.strftime(format="%y"))
print("Month in String: ", date.strftime("%B"))
print("Month in number: ", date.strftime(format="%m"))
print("Date: ", date.strftime(format="%d"))
print("Week day(strftime() sunday=0): ", date.strftime(format="%w"))
print("Hour: ", date.strftime(format="%H"))
print("Minutes: ", date.strftime(format="%M"))
print("Seconds: ", date.strftime(format="%S"))